version: "2"
services:
  httpd:
    hostname: httpd
    build: httpd
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  db:
    hostname: db
    image: mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 1234Qwer
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: 1234Qwer
  redis:
    hostname: redis
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
