"9.2":
  build: ./9.2
  hostname: postgres92
  ports:
    - "5432:5432"
"9.4":
  build: ./9.4
  hostname: postgres94
  ports:
    - "5432:5432"
"9.4-master":
  build: ./9.4-repl
  hostname: postgres94m
  ports:
    - "5432:5432"
  links:
    - "9.4-slave"
"9.4-slave":
  build: ./9.4-repl
  hostname: postgres94s
  ports:
    - "5432:5432"
"9.5":
  build: ./9.5
  hostname: postgres95
  ports:
    - "5432:5432"
